name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    name: Coverage
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.9
          arch: ubuntu-latest
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info